sudo: required
dist: xenial

branches:
  only:
  - master
  - "/^v[0-9]/"

env:
  global:
    - KUBEVIRT_VER=0.9.1

jobs:
  include:
    - stage: Tests
      name: "Default (minikube with K8s v1.11)"

    - name: "minikube (K8s v1.11)"
      env: CPLATFORM=minikube CVER=1.11.3

    - name: "oc cluster (OKD v3.10)"
      env: CPLATFORM=oc_cluster CVER=3.10.0

    - name: "minishift (OKD v3.10)"
      env: CPLATFORM=minishift CVER=3.10.0

    - name: "minikube (K8s v1.10)"
      env: CPLATFORM=minikube CVER=1.10.7

cache:
  directories:
  - cache
  - "~/.minishift/cache"
  - "~/.minikube/cache"

before_script:
## FIXME Workaround for https://github.com/kubernetes/kubernetes/issues/61058
### And https://github.com/LiliC/travis-minikube/blob/e0f26f7b388057f51a0e2558afd5f990e07b6c49/.travis.yml#L11
- sudo mount --make-rshared /

- bash -x ci/prepare-host $CPLATFORM
- bash -x ci/prepare-host virtctl
- bash -x ci/start-cluster $CPLATFORM $CVER
- bash -x ci/deploy-kubevirt $CPLATFORM

script:
- timeout 5m bash -x test.sh
